// Optional authoring helper. Output is ordinary HTML; no framework runs in the browser.
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';
const root = resolve(import.meta.dirname, '..');
const siteUrl = (process.env.SITE_URL || 'https://sajinct.github.io/chemmanoormetals.com').replace(/\/+$/, '');
let home = await readFile(resolve(root, 'index.html'), 'utf8');
const escape = text => String(text).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const prefix = html => html.replace(/(href|src)="(?!https?:|mailto:|tel:|#)([^\"]*)"/g, (_, attr, path) => `${attr}="../${path === './' ? '' : path}"`);
const header = prefix(home.slice(home.indexOf('  <a class="skip-link"'), home.indexOf('  <main'))).replace(' aria-current="page"', '');
const footer = prefix(home.slice(home.indexOf('  <footer'), home.indexOf('</body>')));
const cta = prefix(home.slice(home.indexOf('    <section class="contact-banner"'), home.indexOf('  </main>')));
const pages = [];
const add = (slug, title, summary, content, group = '') => pages.push({ slug, title, summary, content, group });
const link = (path, text, cls = 'text-link') => `<a class="${cls}" href="../${path}">${text} <span aria-hidden="true">↗</span></a>`;
const image = (file, alt, cls = '') => `<img ${cls ? `class="${cls}" ` : ''}src="../assets/${file}" alt="${escape(alt)}" width="1200" height="800" loading="lazy">`;
const section = (content, cls = '') => `<section class="section ${cls}"><div class="container">${content}</div></section>`;
const list = items => `<ul class="feature-list">${items.map(item => `<li>${item}</li>`).join('')}</ul>`;
const productOptions = ['Automatic shutters', 'Automatic gates', 'Moving pergola roofs', 'Perforated shutters', 'Service & maintenance', 'Other enquiry'];
const contactLink = product => link(`contacts/?product=${encodeURIComponent(product)}#enquiry`, 'Discuss your requirements', 'button');

add('products', 'An opening for every possibility.', 'Explore shutters, gates and outdoor solutions for residential, commercial and industrial spaces.',
  section(prefix(home.match(/<div class="product-grid">[\s\S]*?<\/div><\/div><\/section>/)[0].replace('</div></section>', ''))) +
  section(`<div class="section-heading"><div><p class="eyebrow">START WITH YOUR SPACE</p><h2>Let’s find the right fit.</h2></div></div><div class="product-types"><article class="type-card"><h3>For your home</h3><p>Garage shutters, entrance gates and outdoor roofing that fit the way you live.</p></article><article class="type-card"><h3>For your business</h3><p>Rolling and perforated shutters for shopfronts and commercial entrances.</p></article><article class="type-card"><h3>For your industry</h3><p>Shutter and gate options for larger openings and operational requirements.</p></article></div>`), 'Products');

add('automatic-shutters', 'Strength at the touch of a button.', 'Automatic rolling shutters for homes, shops, garages and industrial openings. Made to measure, with your daily use in mind.',
  section(`<div class="split-content"><div class="prose"><p class="eyebrow">AUTOMATIC SHUTTERS</p><h2>Open with ease.<br>Close with confidence.</h2><p>Motor-operated shutters make opening and closing more convenient. Our range includes metal and transparent profiles for different needs, from a private garage to a visible shopfront.</p><p>We help you select a profile and operating arrangement based on the size of your opening, how often it is used and the look you want.</p>${list(['Made to suit the opening and application', 'Side, centre and tubular motor options', 'Installation, operation guidance and maintenance support'])}${contactLink('Automatic shutters')}</div><div class="detail-image">${image('shutter.jpg', 'Wood-tone rolling shutter fitted to a residential garage')}<p class="detail-note">An installation from the Chemmanoor Metals portfolio.</p></div></div>`) +
  section(`<div class="section-heading"><div><p class="eyebrow">SHUTTER OPTIONS</p><h2>A profile for your priorities.</h2></div></div><div class="product-types">${[
    ['Aluminium shutters', 'A metal shutter option for residential and commercial applications. Discuss the finish and profile with our team.'],
    ['Transparent shutters', 'Keep the view and natural light while enclosing an opening. Ask about the available transparent profiles.'],
    ['Garage shutters', 'Make everyday vehicle access more convenient with an opening made for your garage.'],
    ['Window shutters', 'Shutter solutions tailored to window openings and the needs of the space behind them.'],
    ['Grill rolling shutters', 'An open-profile option where ventilation and visibility are part of the requirement.'],
    ['Gear-operated shutters', 'An alternative operating arrangement for appropriate applications. Our team can advise on suitability.']
  ].map(([title, text]) => `<article class="type-card"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div>`), 'Products');

add('automatic-gates', 'A smarter welcome home.', 'Automatic swing and sliding gates that make entering your property more convenient.',
  section(`<div class="split-content"><div class="prose"><p class="eyebrow">AUTOMATIC GATES</p><h2>A good entrance<br>starts with a good fit.</h2><p>Every driveway is different. The width of the entrance, the available clearance and the layout of the site all influence which gate works best.</p><p>Our range includes swing gates and sliding gates. We help you plan the configuration and automation around your property and daily access needs.</p>${list(['Swing gate options with arm or roller mechanisms', 'Normal and telescopic sliding configurations', 'A solution selected for your site and available space'])}${contactLink('Automatic gates')}</div><div class="detail-image">${image('gate.jpg', 'Charcoal horizontal slat sliding gate at a residential driveway')}<p class="detail-note">Sliding gate design from the existing product range.</p></div></div>`) +
  section(`<div class="product-types"><article class="type-card"><h3>Swing gates</h3><p>Gate leaves open through an arc. The site needs adequate clearance for movement.</p></article><article class="type-card"><h3>Sliding gates</h3><p>A gate moves sideways along the entrance. Our team can assess the available run-back space.</p></article><article class="type-card"><h3>Telescopic gates</h3><p>A sliding configuration with multiple sections. Discuss its suitability for your entrance.</p></article></div>`), 'Products');

add('moving-pergola-roof', 'More room for the outdoors.', 'Explore moving pergola roof solutions for patios, terraces and outdoor living areas.',
  section(`<div class="split-content"><div class="prose"><p class="eyebrow">MOVING PERGOLA ROOFS</p><h2>Let your space<br>open up.</h2><p>A moving pergola roof gives you another way to use the space outdoors. Bring your ideas for a patio, terrace or covered seating area, and we’ll discuss the roof arrangement that suits the project.</p><p>See the original product demonstrations to understand the movement, then speak to our team about dimensions, installation and the options available for your site.</p>${list(['Planned around your outdoor area', 'Product demonstrations available', 'Guidance on the right configuration for your project'])}${contactLink('Moving pergola roofs')}</div><div class="detail-image">${image('pergola.jpg', 'Covered patio with a slatted roof and transparent shutter')}<p class="detail-note">An outdoor installation from our portfolio. See the demonstrations for moving roof operation.</p></div></div>`) + section(`${link('video-gallery/#lkqOuCy9EYk', 'Watch the moving pergola demonstration')}`), 'Products');

add('perforated-shutters', 'A more open kind of protection.', 'Perforated shutters for spaces where visibility and ventilation matter alongside a secure closure.',
  section(`<div class="split-content"><div class="prose"><p class="eyebrow">PERFORATED SHUTTERS</p><h2>Let the space<br>breathe.</h2><p>Perforated profiles offer an alternative to a fully solid shutter. Their small openings can allow visibility and airflow while the shutter is closed.</p><p>From shopfronts to residential openings, our team can help you understand the available profiles and choose a solution for your space.</p>${list(['A perforated profile for a more open appearance', 'Options for residential and commercial applications', 'Made to suit the dimensions of your opening'])}${contactLink('Perforated shutters')}</div><div class="detail-image">${image('perforated.jpg', 'White perforated shutter beside a planted residential patio')}<p class="detail-note">Perforated shutter installation from our portfolio.</p></div></div>`) + section(`${link('video-gallery/#CEep9BuAhWc', 'Watch a perforated shutter demonstration')}`), 'Products');

add('company', 'Built on trust.<br>Since 1975.', 'Manufacturing experience, thoughtful service and a commitment to the places we help protect.',
  section(`<div class="split-content"><div>${image('hero-original.jpg', 'A transparent shutter in a Chemmanoor Metals residential installation')}</div><div class="prose"><p class="eyebrow">OUR STORY</p><h2>From Kerala,<br>with lasting purpose.</h2><p>Chemmanoor Metals began in 1975. From our manufacturing base in Thrissur, Kerala, we supply shutters and gates for homes, commercial properties and industrial spaces.</p><p>Our work combines manufacturing, supply and service. We take the time to understand the opening and its use, so the final solution works as part of your space.</p><p>Customization and after-sales support remain central to the way we work, from the first conversation through installation and maintenance.</p>${link('profile/', 'View our company profile')}</div></div>`) +
  section(`<div class="section-heading"><div><p class="eyebrow">WHAT YOU CAN EXPECT</p><h2>A practical approach.<br>From start to finish.</h2></div></div><div class="benefit-grid"><article><span class="benefit-number">01 /</span><h3>Understand</h3><p>Start with your space, its dimensions and the way it needs to work.</p></article><article><span class="benefit-number">02 /</span><h3>Make</h3><p>Select the profile, materials and operating arrangement for the application.</p></article><article><span class="benefit-number">03 /</span><h3>Install</h3><p>Coordinate delivery and fitting, with guidance on everyday operation.</p></article><article><span class="benefit-number">04 /</span><h3>Support</h3><p>Stay connected for servicing, maintenance and questions after installation.</p></article></div>`, 'about-section'), 'Company');

const galleryFiles = ['1-1024x682.jpg', '2-1024x338.jpg', '3-1024x576.jpg', '4-1024x683.jpg', '5-1024x683.jpg', '6.jpg', '7-1024x683.jpg', '9-1024x682.jpg', '10-1024x683.jpg', '11-1024x682.jpg', '12.jpg', '13-1024x576.jpg', '14-1024x683.jpg', '15-1024x576.jpg', '16.jpg', '17-1024x576.jpg', '18-1024x681.jpg', '20-1024x253.jpg', '21-1024x576.jpg', '22-723x1024.jpg', '23-1024x576.jpg', '8-1-1024x768.jpg', '19-1-768x1024.jpg'];
add('photo-gallery', 'Our work.<br>In your world.', 'Explore the Chemmanoor Metals installation portfolio. Select a photograph to take a closer look.',
  section(`<div class="inline-links gallery-links"><span class="eyebrow">23 PROJECT PHOTOGRAPHS</span>${link('video-gallery/', 'Watch product demonstrations')}</div><div class="gallery-grid">${galleryFiles.map((file, index) => `<figure class="gallery-item"><a href="../assets/gallery/${file}" data-gallery aria-label="View installation photograph ${index + 1}">${image(`gallery/${file}`, `Chemmanoor Metals shutter and entrance portfolio, installation photograph ${index + 1}`)}<span aria-hidden="true">↗</span></a><figcaption>Installation ${String(index + 1).padStart(2, '0')}</figcaption></figure>`).join('')}</div><dialog class="lightbox" id="lightbox" aria-label="Installation photograph"><div class="lightbox-bar"><p data-caption></p><button type="button" aria-label="Close photograph">×</button></div><img alt="Selected installation"></dialog>`), 'Our work');

const videos = [
  ['Moving pergola roof', 'lkqOuCy9EYk', 'pergola.jpg'], ['Drizzling with a transparent shutter', 'cxVtzjKBXm8', 'transparent.jpg'],
  ['Transparent rolling shutter', '5ZapdkzbuBM', 'hero-original.jpg'], ['Polycarbonate shutter', 'wCAuweoTlIc', 'banner-2.jpg'],
  ['Rectangular tube garage shutter', 'oKq1ycWZlV0', 'shutter.jpg'], ['An open home with shutters', 'skNgz5YlVyM', 'banner-3.jpg'],
  ['Perforated automatic rolling shutter', 'CEep9BuAhWc', 'perforated.jpg'], ['Automatic main gate', 'XrnX7X-smXs', 'gate.jpg'],
  ['Automatic cantilever aluminium gate', 'rShrpCozW2o', 'gate.jpg'], ['A house with perforated shutters', 'eZU1KsZPAZc', 'project-home.jpg'],
  ['Automatic ladder', '__NXTl3EArE', 'project-home.jpg'], ['Chemmanoor Metals portfolio', 'dFn7VYcGo8M', 'banner-3.jpg'],
  ['Automatic moving pergola', 'LZWzX7HMBR4', 'pergola.jpg'], ['Toughened glass rolling shutter', 'KI4Lu8-5DjQ', 'transparent.jpg'],
  ['Automatic perforated safety shutters', '_Nknu9Famxw', 'perforated.jpg'], ['Opening up a wall at home', '_SYdq22rt9Y', 'hero-original.jpg']
];
add('video-gallery', 'See the movement.<br>Picture the possibilities.', 'Product demonstrations from Chemmanoor Metals. Select play to load a video from YouTube.',
  section(`<div class="video-grid">${videos.map(([title, id, img]) => `<article id="${id}"><div class="video-frame"><button class="video-play" type="button" data-video="${id}" data-title="${escape(title)}" aria-label="Play ${escape(title)}">${image(img, '')}<span class="play-symbol" aria-hidden="true">▶</span><span class="video-play-label">PLAY DEMONSTRATION</span></button></div><h2>${title}</h2><a class="text-link" href="https://www.youtube.com/watch?v=${id}" target="_blank" rel="noopener noreferrer">Watch on YouTube <span aria-hidden="true">↗</span></a></article>`).join('')}</div>`), 'Our work');

const profileVideos = [['Moving pergola roof', 'video001.mp4'], ['Perforated shutter', 'video002.mp4'], ['Transparent shutter', 'video003.mp4'], ['Perforated shutter operation', 'video005.mp4'], ['Transparent shutter operation', 'video9.mp4'], ['Polycarbonate shutter', 'video10.mp4']];
add('profile', 'Chemmanoor Metals.<br>At a glance.', 'Get to know our business, our product range and the team’s practical approach to entrance solutions.',
  section(`<div class="split-content"><div><p class="eyebrow">COMPANY PROFILE</p><h2>Experience behind<br>every opening.</h2><p>Based in Thrissur, we manufacture, supply and service shutters and gates for a wide range of applications.</p>${link('company/', 'Read our story')}</div><table class="profile-table"><tbody><tr><th scope="row">Business</th><td>Chemmanoor Metals</td></tr><tr><th scope="row">Established</th><td>1975</td></tr><tr><th scope="row">Location</th><td>Thrissur, Kerala, India</td></tr><tr><th scope="row">Activities</th><td>Manufacturing, supply, installation and maintenance</td></tr><tr><th scope="row">Products</th><td>Automatic shutters, automatic gates, moving pergola roofs and perforated shutters</td></tr><tr><th scope="row">Applications</th><td>Residential, commercial and industrial</td></tr><tr><th scope="row">Distribution</th><td>Across India; discuss availability for your location with our team.</td></tr></tbody></table></div>`) +
  section(`<div class="section-heading"><div><p class="eyebrow">FROM OUR PROFILE</p><h2>A closer look at our products.</h2></div></div><div class="video-grid">${profileVideos.map(([title, file]) => `<article><video controls preload="none" playsinline aria-label="${title}" poster="../assets/${title.includes('pergola') ? 'pergola.jpg' : title.includes('Perforated') ? 'perforated.jpg' : 'transparent.jpg'}"><source src="https://chemmanoormetals.com/videos/${file}" type="video/mp4">Your browser does not support this video. <a href="https://chemmanoormetals.com/videos/${file}">Open video</a>.</video><h2>${title}</h2><p>Product operation demonstration. No spoken transcript is provided by the original site.</p></article>`).join('')}</div>`), 'Company');

add('clients-feedback', 'Your experience<br>helps us improve.', 'Tell us about your Chemmanoor Metals product, installation or service experience.',
  section(`<div class="split-content"><div class="prose"><p class="eyebrow">CLIENT FEEDBACK</p><h2>We’re here to listen.</h2><p>Whether you have a question, a service request or feedback after installation, we’d like to hear from you.</p><p>Include your name, contact number and a brief description of the product or work so our team can follow up.</p><div class="actions">${link('contacts/#enquiry', 'Share your feedback', 'button')}<a class="text-link" href="tel:+919747070066">Call our team ↗</a></div></div><div class="feedback-panel"><p class="eyebrow">AFTER-SALES SUPPORT</p><h2>Keep your entrance<br>working smoothly.</h2><p>Contact us for maintenance enquiries, product guidance or help with an existing installation.</p><a class="text-link" href="https://wa.me/919747070066" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a></div></div>`));


// The query uses the business name and verified public address rather than an invented map coordinate.
const directions = 'https://www.google.com/maps/search/?api=1&query=Chemmanoor+Metals+Perakam+Thrissur+Kerala+680505';
add('contacts', 'Let’s talk<br>about your space.', 'A new installation, a product question or ongoing maintenance — our team is here to help.',
  section(`<div class="contact-grid"><div><p class="eyebrow">GET IN TOUCH</p><h2>A conversation<br>is a good start.</h2><div class="contact-block"><h3>Give us a call</h3><a href="tel:+919747070066">+91 97470 70066 ↗</a><a href="tel:+919747070055">+91 97470 70055 ↗</a><a href="tel:+914872502666">0487 2502666 ↗</a></div><div class="contact-block"><h3>Send us a message</h3><a href="mailto:mail@chemmanoormetals.com">mail@chemmanoormetals.com ↗</a><a href="https://wa.me/919747070066" target="_blank" rel="noopener noreferrer">Chat on WhatsApp ↗</a></div><div class="contact-block"><h3>Find us in Thrissur</h3><address>Chemmanoor Metals<br>Perakam P.O, Chavakkad Via<br>Thrissur, Kerala – 680505</address><a class="text-link" href="${directions}" target="_blank" rel="noopener noreferrer">Open Google Maps <span aria-hidden="true">↗</span></a></div></div><div id="enquiry" class="enquiry-form"><h2>Tell us what you have in mind.</h2><p>Fill in the details below to prepare an email to our team.</p><form id="enquiry-form" action="mailto:mail@chemmanoormetals.com" method="get"><div class="form-grid"><div class="form-field"><label for="name">Your name *</label><input id="name" name="name" autocomplete="name" maxlength="100" placeholder="Full name" required></div><div class="form-field"><label for="phone">Phone number *</label><input id="phone" name="phone" type="tel" autocomplete="tel" inputmode="tel" minlength="7" maxlength="25" placeholder="Your contact number" required></div><div class="form-field"><label for="email">Email address *</label><input id="email" name="email" type="email" autocomplete="email" maxlength="150" placeholder="you@example.com" required></div><div class="form-field"><label for="location">Project location</label><input id="location" name="location" autocomplete="address-level2" maxlength="150" placeholder="Town or city"></div><div class="form-field full"><label for="product">I’m interested in *</label><select id="product" name="product" required><option value="">Choose a product or service</option>${productOptions.map(p => `<option value="${escape(p)}">${escape(p)}</option>`).join('')}</select></div><div class="form-field full"><label for="message">Project details *</label><textarea id="message" name="message" rows="5" maxlength="1500" placeholder="Tell us about your space, approximate dimensions or what you need help with." required></textarea></div></div><p class="form-note">* Required. This opens your email app with a draft. Your enquiry is only sent when you send that email.</p><button class="button" type="submit">Prepare email enquiry <span aria-hidden="true">↗</span></button><noscript><p>To send your enquiry, please <a href="mailto:mail@chemmanoormetals.com">email our team directly</a> or call one of the numbers above.</p></noscript><div class="form-result" id="form-result" role="status" aria-live="polite" hidden></div></form></div></div>`), 'Contact');

for (const page of pages) {
  const readableTitle = page.title.replaceAll('<br>', ' ');
  const navSlug = { Company: 'company', Products: 'products', 'Our work': 'photo-gallery', Contact: 'contacts' }[page.group];
  const nav = navSlug ? header.replace(`href="../${navSlug}/"`, match => match + (navSlug === page.slug ? ' aria-current="page"' : ' class="active-section"')) : header;
  const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${escape(readableTitle)} | Chemmanoor Metals</title><meta name="description" content="${escape(page.summary)}"><meta name="theme-color" content="#202522"><link rel="canonical" href="${siteUrl}/${page.slug}/"><link rel="icon" href="../assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/styles.css"><script src="../assets/main.js" defer></script></head><body>
${nav}
<main id="main"><section class="page-hero"><div class="container"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="../">Home</a><span aria-hidden="true">/</span><span>${escape(page.slug === 'products' ? 'Products' : page.slug === 'contacts' ? 'Contact' : page.slug.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' '))}</span></nav><h1>${page.title}</h1><p class="lead">${escape(page.summary)}</p></div></section>${page.content}${page.slug === 'contacts' ? '' : cta}</main>${footer}</body></html>`;
  await mkdir(resolve(root, page.slug), { recursive: true });
  await writeFile(resolve(root, page.slug, 'index.html'), html);
}
// Home metadata is derived from one source of truth and remains present with JavaScript disabled.
home = home.replace(/\s*<link rel="canonical"[^>]*>/g, '').replace(/\s*<script type="application\/ld\+json">[\s\S]*?<\/script>/g, '');
const business = { '@context': 'https://schema.org', '@type': 'HomeAndConstructionBusiness', name: 'Chemmanoor Metals', url: siteUrl, telephone: '+919747070066', email: 'mail@chemmanoormetals.com', foundingDate: '1975', address: { '@type': 'PostalAddress', streetAddress: 'Perakam P.O, Chavakkad Via', addressLocality: 'Thrissur', addressRegion: 'Kerala', postalCode: '680505', addressCountry: 'IN' }, sameAs: ['https://www.facebook.com/Chemmanoor-Metals-162917213892981/'] };
home = home.replace('</head>', `  <link rel="canonical" href="${siteUrl}/">\n  <script type="application/ld+json">${JSON.stringify(business)}</script>\n</head>`);
await writeFile(resolve(root, 'index.html'), home);
await writeFile(resolve(root, '404.html'), `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Page not found | Chemmanoor Metals</title><meta name="robots" content="noindex"><style>body{font-family:Arial,sans-serif;color:#222824;text-align:center;padding:12vh 24px;background:#f3f4ef}h1{font-size:6rem;margin:0}h2{font-size:2rem}a{display:inline-block;padding:16px 24px;background:#ff783c;color:#222824;font-weight:bold;text-decoration:none;margin-top:20px}</style></head><body><main><h1>404</h1><h2>This opening leads elsewhere.</h2><p>The page you’re looking for is unavailable.</p><a href="${escape(siteUrl)}/">Back to Chemmanoor Metals ↗</a></main></body></html>`);
const urls = ['', ...pages.map(p => p.slug + '/')];
await writeFile(resolve(root, 'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(path => `<url><loc>${siteUrl}/${path}</loc></url>`).join('')}</urlset>\n`);
await writeFile(resolve(root, 'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`);
console.log(`Created ${pages.length} static pages, metadata and sitemap.`);
